config/routes.rb
Rails.application.routes.draw do
  resources :books
  resources :reservations
  resources :authors
  resources :users

  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :books
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reservations
  belongs_to :author
  accepts_nested_attributes_for :author
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :book
  belongs_to :user
  accepts_nested_attributes_for :user
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :reservation
  has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def create
    @author = Book.create(author_params)

    redirect_to action: "index"
  end

  def book_params
    params.require(:author).permit(:id, :name)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
    @book.author = Author.new
  end

  def show
    @book = Book.find(params[:id])
    @reservation = Reservation.where(:book_id => @book.id)
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)

    redirect_to action: "index"
  end

  def create
    @book = Book.create(book_params)

    redirect_to action: "index"
  end

  def destroy
    Book.find(params[:id]).destroy

   redirect_to action: "index"
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, author_attributes: [:name])
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def index
    @reservation  = Reservation.all
  end

  def new
    @book = Book.find(params[:book_id])
    @reservation = Reservation.new(book_id: @book.id)
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(reservation_params)

    redirect_to action: "index"
  end

  def create
    @reservation = Reservation.create(reservation_params)

    redirect_to action: "index"
  end

  def destroy
    Reservation.find(params[:id]).destroy

   redirect_to action: "index"
  end

  private

  def reservation_params
    params.require(:reservation).permit(:book_id, :checkout_date, :due_date, user_attributes: [:name])
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def create
    @user = Reservation.create(user_params)
  end

  def user_params
    params.require(:user).permit(:id, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/books/create.html.erb
<h1>books#create</h1>

app/views/books/destroy.html.erb
<h1>books#destroy</h1>

app/views/books/edit.html.erb
<p style="color:red">books#edit</p>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.fields_for :authors do |author_form| %>
    <%= author_form.label :author %>
    <%= author_form.text_field :author %>
  <% end %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

<%= link_to "Home", books_path %>

app/views/books/index.html.erb
<p style="color:red">books#index</p>

<%= link_to "View Reservations", reservations_path %>

<%= link_to "Add Book", new_book_path %>


<h1>All Books</h1>

<table style="border:1px solid black">
  <th style="border:1px solid black">Title</th>
  <th style="border:1px solid black">Author</th>
  <th style="border:1px solid black">Edit</th>
  <th style="border:1px solid black">Delete</th>
    <tr>
      <% @books.each do |book| %>
      <td style="border:1px solid black"> <%= link_to book.title, book_path(book.id) %></td>
      <td style="border:1px solid black"> <%= book.author.name %></td>
      <td style="border:1px solid black"> <%= link_to "Edit", edit_book_path(book.id) %> </td>
      <td style="border:1px solid black"> <%= link_to "Delete", book, method: :delete %> </td>
    </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<p style="color:red">books#new</p>

<%= form_for @book do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.fields_for :author do |author_form| %>
    <%= author_form.label :author %>
    <%= author_form.text_field :name %>
  <% end %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.submit %>
<% end %>

<%= link_to "Home", books_path %>

app/views/books/reservations.html.erb
<h1>books#reservations</h1>
<h2>Reservations for this book</h2>

app/views/books/show.html.erb
<p style="color:red">books#show</p>

<h2><%= @book.title %></h2>
<h3>Author: <%= @book.author.name %> </h3>
<h3>Description: <%= @book.description %> </h3>

<%= link_to "Reserve", new_reservation_path(:book_id => @book.id) %>

<%= link_to "Home", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Liberry</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/create.html.erb
<h1>reservations#create</h1>

app/views/reservations/edit.html.erb
<h1>reservations#edit</h1>

<%= form_for @reservation do |f| %>

  <%= f.label :checkout_date %>
  <%= f.date_field :checkout_date %>

  <%= f.label :due_date %>
  <%= f.date_field :due_date %>

  <%= f.submit %>
<% end %>

app/views/reservations/index.html.erb
<p style="color:red">reservations#index</p>

<h1>Reservations:</h1>

<%= link_to "Back to books", books_path %>

<table style="border:1px solid black">
  <th style="border:1px solid black">Book</th>
  <th style="border:1px solid black">Checkout Date</th>
  <th style="border:1px solid black">Due Date</th>
  <th style="border:1px solid black">Edit</th>
  <th style="border:1px solid black">Delete</th>
    <tr>
      <% @reservation.each do |reservation| %>
        <td style="border:1px solid black"> <%= link_to reservation.book.title, reservation_path(reservation.id) %> </td>
        <td style="border:1px solid black"> <%= reservation.checkout_date.strftime("%m/%d") %> </td>
        <td style="border:1px solid black"> <%= reservation.due_date.strftime("%m/%d") %> </td>
        <td style="border:1px solid black"> <%= link_to "Edit", edit_reservation_path(reservation.id) %> </td>
        <td style="border:1px solid black"> <%= link_to "Delete", reservation, method: :delete %> </td>
    </tr>
  <% end %>
</table>

app/views/reservations/new.html.erb
<p style="color:red">reservations#new</p>

<%= form_for @reservation do |f| %>
  <%= f.hidden_field :book_id, :value => @book.id%>

  <%= f.fields_for :user do |user_form| %>
    <%= user_form.label :name %>
    <%= user_form.text_field :name %>
  <% end %>

  <%= f.label :checkout_date %>
  <%= f.date_field :checkout_date %>

  <%= f.label :due_date %>
  <%= f.date_field :due_date %>

  <%= f.submit %>
<% end %>

<%= link_to "Home", reservations_path %>

app/views/reservations/show.html.erb
<p style="color:red">reservations#show</p>

<% if @reservation.due_date.past? == true %>
  <div><h1>OVERDUE!</h1></div>
<% end %>

<h2>Reservation Details</h2>
<h3>Book: <%= @reservation.book.title %> </h3>
<h3>Checkout date: <%= @reservation.checkout_date.strftime("%m/%d") %> </h3>
<h3>Due date: <%= @reservation.due_date.strftime("%m/%d") %> </h3>

<%= link_to "Back to reservations", reservations_path %>